[build]
target = "index.html"
release = true
dist = "dist"
# Enable minification for production builds
minify = "on_release"
filehash = true

[watch]
ignore = ["target", "dist"]

[serve]
address = "127.0.0.1"
port = 8080
open = true

[clean]
dist = "dist"
cargo = true
